POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE0ZWI4YTNiNjgzN2Y2MTU4ZWViNjA3NmU2YThjNDI4YTVmNjJhN2IiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaG9tZS04ZjhmMSIsImF1ZCI6ImhvbWUtOGY4ZjEiLCJhdXRoX3RpbWUiOjE2ODk4NDM3OTMsInVzZXJfaWQiOiJ6Rk90YlUxQ0tmTjRmaWVSYTUwSXZMazRrV3gyIiwic3ViIjoiekZPdGJVMUNLZk40ZmllUmE1MEl2TGs0a1d4MiIsImlhdCI6MTY4OTg0Mzc5MywiZXhwIjoxNjg5ODQ3MzkzLCJwaG9uZV9udW1iZXIiOiIrODQzMjc1MTU4NTkiLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7InBob25lIjpbIis4NDMyNzUxNTg1OSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBob25lIn19.lV6ePXL04UMRUdGUyuzx9JHt97e0S3JAjpEh_ieQjHGiHQjm8Gr4A8R-Qk5e6G9fDGBiXW_BnSh4XNwveLoRObMGV0PFH3D5EDP0bBR95eCyEO0DsQCX_rNEG0uJmUoTT8ZEsBUncRnP4mQzXDSR5u2yFriVLLYRfjXFxegr2gksjJmiNBhu1zfPwGJqUHSxUcaDWOdmokEtvfD9sza7kenvSA_vqPoTd9PSDm7wT-q2oH_BlghrAjpz99HHrklfuQKwpCQSVmVFP-SRdagwE2WhvmkcQvuQT5ihEvE1fp8mVxhceDnnlhUEVbD8jkaGuXVQgKADYlv4kWusVXEAZA"
}