db:
  mongo:
    url: 'mongodb+srv://root:2OtNJk44bvrVTHdL@beta.sqjxdxa.mongodb.net/test_realty'

jwt:
  access_token:
    secret: 'access_token_secret'
    expired_in: '60s'
  refresh_token:
    secret: 'refresh_token_secret'
    expired_in: '365d'

cloud:
  cloudinary:
    url: 'cloudinary://687677691434715:vDkh1Ji_Sici4fkGxl-U7fiMCJ4@dj7btad71'

upload:
  max_number_file_upload: 10
  max_number_file_size: 100000
